from django.urls import path

from myapp import views

app_name = 'myapp'
urlpatterns = [
    path('end/overview/count', views.end.overview.count),
    path('end/book/list', views.end.book.list_api),
    path('end/book/detail', views.end.book.detail),
    path('end/book/create', views.end.book.create),
    path('end/book/update', views.end.book.update),
    path('end/book/delete', views.end.book.delete),
    path('end/comment/list', views.end.comment.list_api),
    path('end/comment/create', views.end.comment.create),
    path('end/comment/update', views.end.comment.update),
    path('end/comment/delete', views.end.comment.delete),
    path('end/classification/list', views.end.classification.list_api),
    path('end/classification/create', views.end.classification.create),
    path('end/classification/update', views.end.classification.update),
    path('end/classification/delete', views.end.classification.delete),
    path('end/tag/list', views.end.tag.list_api),
    path('end/tag/create', views.end.tag.create),
    path('end/tag/update', views.end.tag.update),
    path('end/tag/delete', views.end.tag.delete),
    path('end/record/list', views.end.record.list_api),
    path('end/record/create', views.end.record.create),
    path('end/record/update', views.end.record.update),
    path('end/record/delete', views.end.record.delete),
    path('end/borrow/list', views.end.borrow.list_api),
    path('end/borrow/create', views.end.borrow.create),
    path('end/borrow/update', views.end.borrow.update),
    path('end/borrow/delay', views.end.borrow.delay),
    path('end/borrow/delete', views.end.borrow.delete),
    path('end/loginLog/list', views.end.loginLog.list_api),
    path('end/loginLog/create', views.end.loginLog.create),
    path('end/loginLog/update', views.end.loginLog.update),
    path('end/loginLog/delete', views.end.loginLog.delete),
    path('end/opLog/list', views.end.opLog.list_api),
    path('end/user/list', views.end.user.list_api),
    path('end/user/create', views.end.user.create),
    path('end/user/update', views.end.user.update),
    path('end/user/updatePwd', views.end.user.updatePwd),
    path('end/user/delete', views.end.user.delete),
    path('end/user/info', views.end.user.info),
    path('end/adminLogin', views.end.user.admin_login),
]
