from myapp.views.end.book import *
from myapp.views.end.classification import *
from myapp.views.end.tag import *
from myapp.views.end.user import *
from myapp.views.end.comment import *
from myapp.views.end.record import *
from myapp.views.end.overview import *
from myapp.views.end.loginLog import *
from myapp.views.end.borrow import *
from myapp.views.end.opLog import *
from myapp.views.end.banner import *
